logging:
  ak:
    level: DEBUG
session:
  type: redis
  redis:
    prefix: "ak:crewai-ecs:example:"
    url: "redis://ak-openai-serverless-dev-examples-redis.zinik6.0001.apse2.cache.amazonaws.com:6379"