mcp:
  enabled: true
  port: 8000
  expose_agents: true
  agents: ['*']

logging:
  ak:
    level: WARNING
  system:
    level: WARNING
session:
  type: redis
  redis:
    prefix: "ak:mcp-ecs:example:"
    url: "redis://ak-openai-serverless-dev-examples-redis.qaandw.0001.apse2.cache.amazonaws.com:6379"

    