debug: false

session:
  type: in_memory

tracing:
  enabled: true
  name: ak-py  # global app name

  # per-framework overrides
  frameworks:
    openai:
      name: ak-openai-tracer # tracer name
      provider: traceloop
      variables:             # These are not used in our system still, but the capability is there
        url: https://test-url

    crewai:
      name: ak-crewai-tracer # tracer name
      provider: traceloop

    langgraph:
      provider: traceloop
      name: ak-langgraph


#export AK_TRACING_ENABLED=true
#export AK_TRACING_NAME="ak-py"
#
#export AK_TRACING_FRAMEWORKS_OPENAI_NAME="ak-openai-tracer"
#export AK_TRACING_FRAMEWORKS_OPENAI_PROVIDER="traceloop"
#
#export AK_TRACING_FRAMEWORKS_CREWAI_NAME="ak-crewai-tracer"
#export AK_TRACING_FRAMEWORKS_CREWAI_PROVIDER="traceloop"
#
#export AK_TRACING_FRAMEWORKS_LANGGRAPH_NAME="ak-langgraph-tracer"
#export AK_TRACING_FRAMEWORKS_LANGGRAPH_PROVIDER="traceloop"

