debug: true
session:
  type: dynamodb
execution:
  mode: rest_sync
  queues:
    input:
      # url: "https://sqs.<region>.amazonaws.com/<account-id>/<input-queue-name>"
      max_receive_count: 3
    output:
      # url: "https://sqs.<region>.amazonaws.com/<account-id>/<output-queue-name>"
      max_receive_count: 3
  response_store:
    type: dynamodb
    retry_count: 5
    delay: 5
    # dynamodb:
      # table_name: "<your table name>"
      # ttl: 30