debug: true
session:
  type: redis
  redis:
    prefix: "ak:openai:example:"
    url: "redis://ak-openai-serverless-dev-examples-redis.qaandw.0001.apse2.cache.amazonaws.com:6379"
execution:
  mode: rest_sync
  queues:
    # input_queue_url: "https://sqs.<region>.amazonaws.com/<account-id>/<input-queue-name>"
    # output_queue_url: "https://sqs.<region>.amazonaws.com/<account-id>/<output-queue-name>"
    input_queue_max_receive_count: 3
    output_queue_max_receive_count: 3
  response_store:
    retry_count: 5
    delay: 5
    # dynamodb:
      # table_name: "<your table name>"
      # ttl: 30