logging:
  ak:
    level: DEBUG
session:
  type: redis
  redis:
    prefix: "ak:openai:example:"
    url: "redis://ak-openai-serverless-dev-examples-redis.zinik6.0001.apse2.cache.amazonaws.com:6379"
execution:
  mode: rest_sync
  queues:
    input:
      # url: "https://sqs.<region>.amazonaws.com/<account-id>/<input-queue-name>"
      max_receive_count: 3
    output:
      # url: "https://sqs.<region>.amazonaws.com/<account-id>/<output-queue-name>"
      max_receive_count: 3
  response_store:
    type: dynamodb
    retry_count: 5
    delay: 5
    # dynamodb:
      # table_name: "<your table name>"
      # ttl: 30