"""
Pluggable thread naming for Conversation Thread Support.

When a thread is auto-created without an explicit thread_name, its display name
is generated by the active ThreadNamingStrategy: a single LiteLLM call derives
a concise title from the first prompt (model from thread.naming.model), falling
back to a truncated prompt prefix whenever the call cannot happen (litellm
missing, no API key, model error) — naming never fails thread creation.

End users replace the default by subclassing and registering their own strategy
at startup — e.g. keep the LLM call machinery and swap the prompt:

    class MyNaming(ThreadNamingStrategy):
        def build_instruction(self, prompt: str) -> str:
            return f"Reply with a three-word title for: {prompt}"

    ConversationThreadManager.set_naming_strategy(MyNaming())

or override generate_name entirely for any other logic (optionally calling
self._complete for the LLM call).

The strategy runs only at thread creation, and never for threads whose name was
explicitly supplied (name_locked) — see docs/specs/348-conversation-thread-support/design.md.
"""

import importlib.util
import logging

from ...core.config import AKConfig

# Fallback when thread support is not configured (naming config unavailable).
_DEFAULT_MAX_NAME_LENGTH = 80

_LITELLM_MISSING_WARNING = (
    "litellm is not installed — LLM-based thread naming is unavailable and thread names "
    'will fall back to a truncated prompt prefix. Install it with: pip install "agentkernel[thread]"'
)


def _max_name_length() -> int:
    """Return the configured maximum auto-generated name length."""
    thread_config = AKConfig.get().thread
    return thread_config.naming.max_length if thread_config is not None else _DEFAULT_MAX_NAME_LENGTH


class ThreadNamingStrategy:
    """
    Default naming strategy for auto-created threads, and the base class for
    user-supplied strategies: derives a concise thread title from the first
    prompt with a single LiteLLM call (model from thread.naming.model, API keys
    from the environment), so a gibberish first prompt never becomes the thread
    name. Naming never fails thread creation — any error falls back to a
    truncated prompt prefix.

    Custom strategies reuse the call machinery by overriding build_instruction
    to change the prompt, or override generate_name and call self._complete.
    """

    _log = logging.getLogger("ak.thread.naming")

    def __init__(self):
        """
        Initializes the strategy. When this instance will run the default
        LLM-based generate_name and litellm is not installed, warn loudly at
        construction (i.e. at startup, once) instead of only at call time —
        silently degrading to the truncation fallback is not obvious otherwise.
        """
        uses_default_llm_naming = type(self).generate_name is ThreadNamingStrategy.generate_name
        if uses_default_llm_naming and importlib.util.find_spec("litellm") is None:
            self._log.warning(_LITELLM_MISSING_WARNING)

    def generate_name(self, prompt: str) -> str:
        """
        Generate a thread name from the first prompt via an LLM call, falling
        back to a truncated prompt prefix when the call cannot be made.
        :param prompt: The first prompt of the session.
        :return: The generated thread name.
        """
        prompt = (prompt or "").strip()
        if not prompt:
            return ""
        try:
            name = self._complete(self.build_instruction(prompt))
        except ImportError:
            self._log.warning(_LITELLM_MISSING_WARNING)
            return self._truncate(prompt)
        except Exception as e:
            self._log.warning(f"LLM thread naming failed ({e}); falling back to a truncated prompt prefix")
            return self._truncate(prompt)
        name = name.strip().strip("\"'").strip()
        if not name:
            return self._truncate(prompt)
        # Cap the LLM output with the same word-boundary rule as the fallback.
        return self._truncate(name)

    def build_instruction(self, prompt: str) -> str:
        """
        Build the instruction sent to the naming model. Override to customise
        the prompt while keeping the built-in call machinery.
        :param prompt: The first prompt of the session.
        :return: The instruction for the naming model.
        """
        return (
            f"Generate a concise title (at most {_max_name_length()} characters) for a conversation "
            "that starts with the message below. Reply with the title only — no quotes, no punctuation "
            "at the end. If the message is gibberish or meaningless, reply exactly: New conversation\n\n"
            f"Message: {prompt}"
        )

    def _complete(self, instruction: str) -> str:
        """
        Make the naming LLM call via LiteLLM using thread.naming.model. API
        keys are read from the environment (LiteLLM convention). Reusable by
        custom strategies for their own naming logic.
        :param instruction: The instruction to send to the model.
        :return: The model's reply text.
        """
        import litellm  # optional dependency — imported lazily so naming degrades to the fallback without it

        response = litellm.completion(
            model=AKConfig.get().thread.naming.model,
            messages=[{"role": "user", "content": instruction}],
            max_tokens=50,
        )
        return response.choices[0].message.content or ""

    @staticmethod
    def _truncate(text: str) -> str:
        """
        Fallback naming rule, also used to cap LLM output: the first
        thread.naming.max_length characters (default 80), trimmed to the last
        word boundary and suffixed with an ellipsis when cut.
        :param text: The text to derive the name from.
        :return: The truncated name.
        """
        max_length = _max_name_length()
        text = (text or "").strip()
        if len(text) <= max_length:
            return text
        cut = text[:max_length]
        if " " in cut:
            cut = cut.rsplit(" ", 1)[0]
        return f"{cut}…"
