execution:
  mode: realtime
  queues:
    type: nats
    nats:
      url: "nats://localhost:4222"
      input_stream: AGENT_REQUESTS
      input_subject_prefix: chat.req
      output_stream: AGENT_REPLIES
      output_subject_prefix: chat.out
      partitions: 1
      ack_wait: 300
      retry_backoff: 1.0
      duplicate_window: 300
      auto_provision: true

    input:
      max_receive_count: 2
      no_of_consumers: 1

    output:
      no_of_consumers: 1
