logging:
  ak:
    level: DEBUG
session:
  type: redis
  redis:
    prefix: "ak:crewai-auth-ecs:example:"
    url: "redis://ak-openai-serverless-dev-examples-redis.rhjs7r.0001.use2.cache.amazonaws.com:6379"