region        = "ap-southeast-2"
product_alias = "ak-oai-ddb-ecs"
env_alias     = "dev"
module_name   = "examples"
ecr_image_uri = "329597159169.dkr.ecr.ap-southeast-2.amazonaws.com/openai-dynamodb-ext:latest"